# Generated by Django 4.0 on 2022-01-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobpost_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_rejected_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
