# Generated by Django 4.0 on 2021-12-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobpost_job_expired_jobpost_job_rejected_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='jobpost',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_for_month',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_payment_id', to='jobs.payments'),
        ),
    ]
