# Generated by Django 4.0 on 2022-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_payments_jobpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_uid',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
