# Generated by Django 4.0 on 2022-01-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_payments_payment_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='payment_uid',
            new_name='payment_note',
        ),
    ]
