# Generated by Django 4.0 on 2021-12-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('job_detail', models.CharField(max_length=200)),
                ('job_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_for_month', models.CharField(max_length=200)),
                ('payment_amount', models.IntegerField(default=0)),
                ('payment_date', models.DateTimeField(verbose_name='payment date')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost')),
            ],
        ),
    ]
