# Generated by Django 4.0 on 2021-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_taken',
            field=models.BooleanField(default=False),
        ),
    ]
