# Generated by Django 4.0 on 2021-12-18 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0002_jobpost_job_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_taker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
