# Generated by Django 4.0 on 2021-12-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobpost_job_taker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_done_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date job completed'),
        ),
    ]
