# Generated by Django 4.0 on 2021-12-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobs', '0005_jobpost_job_done_jobpost_job_done_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_author', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_user', to='auth.user'),
        ),
    ]
