# Generated by Django 4.0 on 2022-01-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobpost_job_passed_review_jobpost_job_taken_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
